language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
cache: pip
install:
  - pip install --upgrade pipenv
  - pipenv install --dev --skip-lock
script: pipenv run nosetests --with-coverage --cover-erase --cover-html --cover-package shuffled tests
