language: python
cache: pip
os: linux
python:
  - "2.7"
  - "3.4"
jobs:
  include:
    - python: "3.8"
      script:
        - pip install black mypy
        - make check
install: pip install --editable .[dev]
script:
  - make check-tests
