name: main
on: [push]
jobs:
  check-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', 'pypy3']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip poetry
      - run: poetry install --extras tests
      - run: poetry run make check-tests
  check-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install --upgrade pip poetry
      - run: poetry install --extras dev
      - run: poetry run make check-lint
      - run: poetry run make check-format
      - run: poetry run poetry build
  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [check-tests, check-dev]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install --upgrade pip poetry
      - run: poetry run poetry build
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
